//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh ứng dụng.
        /// </summary>
        internal static string anhungdung {
            get {
                return ResourceManager.GetString("anhungdung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BỘ SƯU TẬP.
        /// </summary>
        internal static string bosuutap {
            get {
                return ResourceManager.GetString("bosuutap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÁC LOẠI BỀ MẶT.
        /// </summary>
        internal static string cacloaibemat {
            get {
                return ResourceManager.GetString("cacloaibemat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        internal static string chitiet {
            get {
                return ResourceManager.GetString("chitiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có thể bạn quan tâm.
        /// </summary>
        internal static string cothebanquantam {
            get {
                return ResourceManager.GetString("cothebanquantam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string diachi {
            get {
                return ResourceManager.GetString("diachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐỘ DÀY TIÊU CHUẨN.
        /// </summary>
        internal static string dodaytieuchuan {
            get {
                return ResourceManager.GetString("dodaytieuchuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giải pháp.
        /// </summary>
        internal static string giaiphap {
            get {
                return ResourceManager.GetString("giaiphap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        internal static string gioithieu {
            get {
                return ResourceManager.GetString("gioithieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi thông tin.
        /// </summary>
        internal static string guithongtin {
            get {
                return ResourceManager.GetString("guithongtin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi thông tin tới chúng tôi.
        /// </summary>
        internal static string guithongtintoichungtoi {
            get {
                return ResourceManager.GetString("guithongtintoichungtoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        internal static string hinhanh {
            get {
                return ResourceManager.GetString("hinhanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối với chúng tôi.
        /// </summary>
        internal static string ketnoivschungtoi {
            get {
                return ResourceManager.GetString("ketnoivschungtoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng - đối tác.
        /// </summary>
        internal static string khachangdoitac {
            get {
                return ResourceManager.GetString("khachangdoitac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KÍCH THƯỚC.
        /// </summary>
        internal static string kichthuoc {
            get {
                return ResourceManager.GetString("kichthuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string lienhe {
            get {
                return ResourceManager.GetString("lienhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ với chúng tôi.
        /// </summary>
        internal static string lienhevschungtoi {
            get {
                return ResourceManager.GetString("lienhevschungtoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu ứng dụng.
        /// </summary>
        internal static string mauungdung {
            get {
                return ResourceManager.GetString("mauungdung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác nhận.
        /// </summary>
        internal static string maxacnhan {
            get {
                return ResourceManager.GetString("maxacnhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới.
        /// </summary>
        internal static string moi {
            get {
                return ResourceManager.GetString("moi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string mota {
            get {
                return ResourceManager.GetString("mota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        internal static string sanpham {
            get {
                return ResourceManager.GetString("sanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm cùng danh mục.
        /// </summary>
        internal static string sanphamcungdanhmuc {
            get {
                return ResourceManager.GetString("sanphamcungdanhmuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông số kỹ thuật.
        /// </summary>
        internal static string thongsokythuat {
            get {
                return ResourceManager.GetString("thongsokythuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm đại lý.
        /// </summary>
        internal static string timdaily {
            get {
                return ResourceManager.GetString("timdaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ỨNG DỤNG CỦA.
        /// </summary>
        internal static string ungdungcua {
            get {
                return ResourceManager.GetString("ungdungcua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ưu điểm.
        /// </summary>
        internal static string uudiem {
            get {
                return ResourceManager.GetString("uudiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem bộ sưu tập.
        /// </summary>
        internal static string xembosuutap {
            get {
                return ResourceManager.GetString("xembosuutap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem hình ảnh.
        /// </summary>
        internal static string xemhinhanh {
            get {
                return ResourceManager.GetString("xemhinhanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tất cả.
        /// </summary>
        internal static string xemtatca {
            get {
                return ResourceManager.GetString("xemtatca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        internal static string xemthem {
            get {
                return ResourceManager.GetString("xemthem", resourceCulture);
            }
        }
    }
}
