//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class API
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Object { get; set; }
        public Nullable<bool> IsList { get; set; }
        public string Paramaster { get; set; }
        public Nullable<int> WidgetID { get; set; }
        public string ObjItem { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
        public string Value { get; set; }
        public Nullable<int> FileID { get; set; }
    
        public virtual FDI_File FDI_File { get; set; }
        public virtual Widget Widget { get; set; }
    }
}
