//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.DN_RequestWare = new HashSet<DN_RequestWare>();
            this.Markets = new HashSet<Market>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Coordinates { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CityID { get; set; }
    
        public virtual DN_Agency DN_Agency { get; set; }
        public virtual System_City System_City { get; set; }
        public virtual ICollection<DN_RequestWare> DN_RequestWare { get; set; }
        public virtual ICollection<Market> Markets { get; set; }
    }
}
