//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeOption
    {
        public int ID { get; set; }
        public Nullable<int> ProductDetailID { get; set; }
        public string Values { get; set; }
        public Nullable<int> ControlValuesID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUserName { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUserName { get; set; }
        public string LanguageId { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<int> AttributeID { get; set; }
    
        public virtual DN_AttributeDynamic DN_AttributeDynamic { get; set; }
        public virtual Shop_Product_Detail Shop_Product_Detail { get; set; }
    }
}
