//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.Author_Product = new HashSet<Author_Product>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> DateCreate { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Slug { get; set; }
    
        public virtual ICollection<Author_Product> Author_Product { get; set; }
    }
}
