//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.OrderCars = new HashSet<OrderCar>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string CarType { get; set; }
        public string Phone { get; set; }
        public int Quantity { get; set; }
        public string Address { get; set; }
        public Nullable<long> Latitude { get; set; }
        public Nullable<long> Longitude { get; set; }
        public int UnitID { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual DN_Unit DN_Unit { get; set; }
        public virtual ICollection<OrderCar> OrderCars { get; set; }
    }
}
