//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashOutWallet
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> DateCreate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Type { get; set; }
        public string Query { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Code { get; set; }
        public Nullable<int> OrderPaketID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
