//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Recipe
    {
        public Category_Recipe()
        {
            this.Category_Product_Recipe = new HashSet<Category_Product_Recipe>();
            this.Mapping_Category_Recipe = new HashSet<Mapping_Category_Recipe>();
            this.P_Workshop = new HashSet<P_Workshop>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> Totalkg { get; set; }
        public Nullable<decimal> TotalPercent { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> DateCreate { get; set; }
        public Nullable<decimal> DateUpdate { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<bool> IsUse { get; set; }
        public Nullable<decimal> TotalPriceFinal { get; set; }
        public Nullable<decimal> TotalIncurred { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Category_Product_Recipe> Category_Product_Recipe { get; set; }
        public virtual DN_Users DN_Users { get; set; }
        public virtual ICollection<Mapping_Category_Recipe> Mapping_Category_Recipe { get; set; }
        public virtual ICollection<P_Workshop> P_Workshop { get; set; }
    }
}
