//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cate_Value
    {
        public Cate_Value()
        {
            this.DN_RequestWarehousing = new HashSet<DN_RequestWarehousing>();
            this.Gallery_Video = new HashSet<Gallery_Video>();
            this.Product_Value = new HashSet<Product_Value>();
            this.Shop_Order_Details = new HashSet<Shop_Order_Details>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CateID { get; set; }
        public string Barcode { get; set; }
        public Nullable<decimal> PriceNew { get; set; }
        public Nullable<decimal> PriceCost { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
        public Nullable<decimal> DateImport { get; set; }
        public Nullable<int> StorageProductID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<decimal> QuantityOut { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string Code { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.Guid> RequestWareID { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> PriceUnit { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual Category Category { get; set; }
        public virtual DN_Agency DN_Agency { get; set; }
        public virtual DN_RequestWare DN_RequestWare { get; set; }
        public virtual DN_Unit DN_Unit { get; set; }
        public virtual StorageProduct StorageProduct { get; set; }
        public virtual ICollection<DN_RequestWarehousing> DN_RequestWarehousing { get; set; }
        public virtual ICollection<Gallery_Video> Gallery_Video { get; set; }
        public virtual ICollection<Product_Value> Product_Value { get; set; }
        public virtual ICollection<Shop_Order_Details> Shop_Order_Details { get; set; }
    }
}
