//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Cate_Value = new HashSet<Cate_Value>();
            this.DN_SupplierProduct = new HashSet<DN_SupplierProduct>();
            this.OrderCars = new HashSet<OrderCar>();
            this.PolicyAgencies = new HashSet<PolicyAgency>();
            this.Produces = new HashSet<Produce>();
            this.ProduceProductPrepares = new HashSet<ProduceProductPrepare>();
            this.SupplierAmountProducts = new HashSet<SupplierAmountProduct>();
            this.TotalProductToDays = new HashSet<TotalProductToDay>();
            this.Category1 = new HashSet<Category>();
            this.Category_Recipe = new HashSet<Category_Recipe>();
            this.DN_RequestWare = new HashSet<DN_RequestWare>();
            this.FAQ_Question = new HashSet<FAQ_Question>();
            this.Gallery_Picture1 = new HashSet<Gallery_Picture>();
            this.Gallery_Video = new HashSet<Gallery_Video>();
            this.Mapping_Category_Recipe = new HashSet<Mapping_Category_Recipe>();
            this.Shop_Product = new HashSet<Shop_Product>();
            this.Shop_Product_Detail = new HashSet<Shop_Product_Detail>();
            this.StorageProducts = new HashSet<StorageProduct>();
            this.TotalStorageWares = new HashSet<TotalStorageWare>();
            this.DN_AttributeDynamic = new HashSet<DN_AttributeDynamic>();
            this.News_News = new HashSet<News_News>();
            this.Shop_Product_Detail1 = new HashSet<Shop_Product_Detail>();
            this.DN_Promotion = new HashSet<DN_Promotion>();
            this.DN_Sale = new HashSet<DN_Sale>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public Nullable<int> PictureID { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
        public string Icon { get; set; }
        public Nullable<int> IsLevel { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsMenu { get; set; }
        public Nullable<bool> IsMenuFooter { get; set; }
        public Nullable<int> Sort { get; set; }
        public string SEOTitle { get; set; }
        public string SEODescription { get; set; }
        public string SEOKeyword { get; set; }
        public string LanguageId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UserCreate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsShowhome { get; set; }
        public Nullable<decimal> Percent { get; set; }
        public Nullable<decimal> PriceCost { get; set; }
        public Nullable<decimal> Incurred { get; set; }
        public Nullable<decimal> WeightDefault { get; set; }
        public Nullable<decimal> PercentLoss { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> PriceRecipe { get; set; }
        public Nullable<decimal> PriceOld { get; set; }
        public Nullable<int> Profit { get; set; }
        public Nullable<decimal> PriceFinal { get; set; }
        public Nullable<decimal> PriceRecipeFinal { get; set; }
        public Nullable<decimal> TotalIncurredFinal { get; set; }
        public Nullable<bool> IsShowApp { get; set; }
    
        public virtual ICollection<Cate_Value> Cate_Value { get; set; }
        public virtual DN_Unit DN_Unit { get; set; }
        public virtual ICollection<DN_SupplierProduct> DN_SupplierProduct { get; set; }
        public virtual ICollection<OrderCar> OrderCars { get; set; }
        public virtual ICollection<PolicyAgency> PolicyAgencies { get; set; }
        public virtual ICollection<Produce> Produces { get; set; }
        public virtual ICollection<ProduceProductPrepare> ProduceProductPrepares { get; set; }
        public virtual ICollection<SupplierAmountProduct> SupplierAmountProducts { get; set; }
        public virtual ICollection<TotalProductToDay> TotalProductToDays { get; set; }
        public virtual ICollection<Category> Category1 { get; set; }
        public virtual Category Category2 { get; set; }
        public virtual Gallery_Picture Gallery_Picture { get; set; }
        public virtual ICollection<Category_Recipe> Category_Recipe { get; set; }
        public virtual ICollection<DN_RequestWare> DN_RequestWare { get; set; }
        public virtual ICollection<FAQ_Question> FAQ_Question { get; set; }
        public virtual ICollection<Gallery_Picture> Gallery_Picture1 { get; set; }
        public virtual ICollection<Gallery_Video> Gallery_Video { get; set; }
        public virtual ICollection<Mapping_Category_Recipe> Mapping_Category_Recipe { get; set; }
        public virtual ICollection<Shop_Product> Shop_Product { get; set; }
        public virtual ICollection<Shop_Product_Detail> Shop_Product_Detail { get; set; }
        public virtual ICollection<StorageProduct> StorageProducts { get; set; }
        public virtual ICollection<TotalStorageWare> TotalStorageWares { get; set; }
        public virtual ICollection<DN_AttributeDynamic> DN_AttributeDynamic { get; set; }
        public virtual ICollection<News_News> News_News { get; set; }
        public virtual ICollection<Shop_Product_Detail> Shop_Product_Detail1 { get; set; }
        public virtual ICollection<DN_Promotion> DN_Promotion { get; set; }
        public virtual ICollection<DN_Sale> DN_Sale { get; set; }
    }
}
