//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CookieLogin
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string key { get; set; }
        public string Value { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsFacebook { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
