//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost_Product
    {
        public int ID { get; set; }
        public Nullable<int> SetupProductId { get; set; }
        public Nullable<decimal> Percent { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> BiasProduceID { get; set; }
    
        public virtual BiasProduce BiasProduce { get; set; }
        public virtual SetupProduction SetupProduction { get; set; }
        public virtual Shop_Product Shop_Product { get; set; }
    }
}
