//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CostType()
        {
            this.PaymentVouchers = new HashSet<PaymentVoucher>();
            this.ReceiptPayments = new HashSet<ReceiptPayment>();
            this.ReceiptVouchers = new HashSet<ReceiptVoucher>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.Guid> UserCreate { get; set; }
        public Nullable<decimal> DateCreate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Percent { get; set; }
        public Nullable<bool> IsUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentVoucher> PaymentVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptPayment> ReceiptPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptVoucher> ReceiptVouchers { get; set; }
    }
}
