//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRating
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerRating()
        {
            this.Gallery_Picture = new HashSet<Gallery_Picture>();
        }
    
        public int ID { get; set; }
        public int ShopId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int TypeRating { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gallery_Picture> Gallery_Picture { get; set; }
    }
}
