//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_TypeGroup
    {
        public Customer_TypeGroup()
        {
            this.Customer_Type = new HashSet<Customer_Type>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Customer_Type> Customer_Type { get; set; }
    }
}
