//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Review_Deltails
    {
        public int ID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public Nullable<int> PointID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Rep { get; set; }
    
        public virtual Customer_Point Customer_Point { get; set; }
        public virtual Customer_question Customer_question { get; set; }
        public virtual Customer_Review Customer_Review { get; set; }
    }
}
