//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_LastOrder
    {
        public Nullable<long> RowNumber { get; set; }
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
    }
}
