//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Groups
    {
        public Customer_Groups()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<bool> IsAgency { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
