//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Reward
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<decimal> PriceReward { get; set; }
        public Nullable<decimal> PriceReceive { get; set; }
        public Nullable<decimal> TotalCP { get; set; }
        public Nullable<decimal> PriceReceiver { get; set; }
        public Nullable<decimal> CashOutWallet { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DN_Agency DN_Agency { get; set; }
    }
}
