//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public CustomerAddress()
        {
            this.Shop_Orders = new HashSet<Shop_Orders>();
            this.Shop_Product = new HashSet<Shop_Product>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public bool IsDefault { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int AddressType { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Commune { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Shop_Orders> Shop_Orders { get; set; }
        public virtual ICollection<Shop_Product> Shop_Product { get; set; }
    }
}
