//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_History
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CustomerActionID { get; set; }
        public string CustomerLink { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
    
        public virtual Customer_Action Customer_Action { get; set; }
    }
}
