//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Active
    {
        public DN_Active()
        {
            this.DN_Role_ModuleActive = new HashSet<DN_Role_ModuleActive>();
            this.DN_User_ModuleActive = new HashSet<DN_User_ModuleActive>();
            this.DN_Roles = new HashSet<DN_Roles>();
        }
    
        public int ID { get; set; }
        public string NameActive { get; set; }
        public Nullable<int> Ord { get; set; }
    
        public virtual ICollection<DN_Role_ModuleActive> DN_Role_ModuleActive { get; set; }
        public virtual ICollection<DN_User_ModuleActive> DN_User_ModuleActive { get; set; }
        public virtual ICollection<DN_Roles> DN_Roles { get; set; }
    }
}
