//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Agency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DN_Agency()
        {
            this.Agency_Module = new HashSet<Agency_Module>();
            this.Areas = new HashSet<Area>();
            this.Cate_Value = new HashSet<Cate_Value>();
            this.Customers = new HashSet<Customer>();
            this.Customer_Reward = new HashSet<Customer_Reward>();
            this.DN_ImportProduct = new HashSet<DN_ImportProduct>();
            this.DN_RequestWare = new HashSet<DN_RequestWare>();
            this.DN_Roles = new HashSet<DN_Roles>();
            this.DN_Setting = new HashSet<DN_Setting>();
            this.DN_Supplier = new HashSet<DN_Supplier>();
            this.DN_Users = new HashSet<DN_Users>();
            this.Documents = new HashSet<Document>();
            this.Product_Value = new HashSet<Product_Value>();
            this.RewardAgencyHistories = new HashSet<RewardAgencyHistory>();
            this.RewardHistories = new HashSet<RewardHistory>();
            this.Shop_ContactOrder = new HashSet<Shop_ContactOrder>();
            this.Shop_Orders = new HashSet<Shop_Orders>();
            this.StorageWarehousings = new HashSet<StorageWarehousing>();
            this.Wallet_Agency = new HashSet<Wallet_Agency>();
            this.Gallery_Picture = new HashSet<Gallery_Picture>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EnterpriseID { get; set; }
        public string Name { get; set; }
        public string Latitute { get; set; }
        public string Longitude { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }
        public string Address { get; set; }
        public string Company { get; set; }
        public string MST { get; set; }
        public string STK { get; set; }
        public string FullnameBank { get; set; }
        public string Branchname { get; set; }
        public string BankName { get; set; }
        public Nullable<decimal> CreateDate { get; set; }
        public Nullable<decimal> DateStart { get; set; }
        public Nullable<decimal> DateEnd { get; set; }
        public Nullable<decimal> DateLock { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public Nullable<bool> IsOut { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Code { get; set; }
        public string IPTimekeep { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<bool> IsModule { get; set; }
        public Nullable<bool> IsWholeSale { get; set; }
        public Nullable<int> AgencyLevelId { get; set; }
        public string Coordinates { get; set; }
        public Nullable<decimal> WalletValue { get; set; }
        public Nullable<decimal> CashOut { get; set; }
        public Nullable<int> MarketID { get; set; }
        public Nullable<bool> IsFdi { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ListID { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string TokenDevice { get; set; }
        public string AvatarUrl { get; set; }
        public string ImageTimeline { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agency_Module> Agency_Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Area> Areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cate_Value> Cate_Value { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Reward> Customer_Reward { get; set; }
        public virtual DN_Enterprises DN_Enterprises { get; set; }
        public virtual DN_GroupAgency DN_GroupAgency { get; set; }
        public virtual Market Market { get; set; }
        public virtual ST_Group ST_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_ImportProduct> DN_ImportProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_RequestWare> DN_RequestWare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Roles> DN_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Setting> DN_Setting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Supplier> DN_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Users> DN_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Value> Product_Value { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RewardAgencyHistory> RewardAgencyHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RewardHistory> RewardHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_ContactOrder> Shop_ContactOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_Orders> Shop_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageWarehousing> StorageWarehousings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wallet_Agency> Wallet_Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gallery_Picture> Gallery_Picture { get; set; }
    }
}
