//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_CabinetDocument
    {
        public DN_CabinetDocument()
        {
            this.DN_Drawer = new HashSet<DN_Drawer>();
            this.Documents = new HashSet<Document>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> AgencyID { get; set; }
    
        public virtual DN_DocumentRoom DN_DocumentRoom { get; set; }
        public virtual ICollection<DN_Drawer> DN_Drawer { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
    }
}
