//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Calendar_Weekly_Schedule
    {
        public int ID { get; set; }
        public Nullable<int> CalenderID { get; set; }
        public Nullable<int> MWSID { get; set; }
        public Nullable<int> AgencyID { get; set; }
    
        public virtual DN_Calendar DN_Calendar { get; set; }
        public virtual DN_Weekly_Schedule DN_Weekly_Schedule { get; set; }
    }
}
