//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_ConfigMonth
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> QuantityDay { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string Description { get; set; }
    }
}
