//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Combo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DN_Combo()
        {
            this.Shop_ContactOrder_Details = new HashSet<Shop_ContactOrder_Details>();
            this.Shop_Order_Details = new HashSet<Shop_Order_Details>();
            this.Shop_Product = new HashSet<Shop_Product>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DateStart { get; set; }
        public Nullable<decimal> DateEnd { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> PictureID { get; set; }
        public Nullable<decimal> Percent { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public string Content { get; set; }
    
        public virtual Gallery_Picture Gallery_Picture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_ContactOrder_Details> Shop_ContactOrder_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_Order_Details> Shop_Order_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_Product> Shop_Product { get; set; }
    }
}
