//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Department
    {
        public DN_Department()
        {
            this.DN_UsersInRoles = new HashSet<DN_UsersInRoles>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<decimal> DateCreate { get; set; }
    
        public virtual ICollection<DN_UsersInRoles> DN_UsersInRoles { get; set; }
    }
}
