//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_DocumentLevel
    {
        public DN_DocumentLevel()
        {
            this.DN_DocumentRoom = new HashSet<DN_DocumentRoom>();
            this.Documents = new HashSet<Document>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> Level { get; set; }
        public string NameLevel { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<DN_DocumentRoom> DN_DocumentRoom { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
    }
}
