//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_EDIT_Schedule
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> Date { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<decimal> Datecreated { get; set; }
        public Nullable<System.Guid> UserChangeId { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<int> DayOffId { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual DN_Schedule DN_Schedule { get; set; }
        public virtual DN_Users DN_Users { get; set; }
        public virtual DN_Users DN_Users1 { get; set; }
    }
}
