//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_GroupAgency
    {
        public DN_GroupAgency()
        {
            this.DN_Agency = new HashSet<DN_Agency>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<DN_Agency> DN_Agency { get; set; }
    }
}
