//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Level
    {
        public DN_Level()
        {
            this.DN_Roles = new HashSet<DN_Roles>();
            this.DN_Room = new HashSet<DN_Room>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<DN_Roles> DN_Roles { get; set; }
        public virtual ICollection<DN_Room> DN_Room { get; set; }
    }
}
