//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DN_Module()
        {
            this.Agency_Module = new HashSet<Agency_Module>();
            this.DN_Module1 = new HashSet<DN_Module>();
            this.DN_Role_ModuleActive = new HashSet<DN_Role_ModuleActive>();
            this.DN_User_ModuleActive = new HashSet<DN_User_ModuleActive>();
            this.DN_Roles = new HashSet<DN_Roles>();
            this.DN_Users = new HashSet<DN_Users>();
            this.ST_Group = new HashSet<ST_Group>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string NameModule { get; set; }
        public string Link { get; set; }
        public string ClassCss { get; set; }
        public Nullable<int> Ord { get; set; }
        public string Content { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Level { get; set; }
        public string NameLevel { get; set; }
        public Nullable<bool> IsAll { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agency_Module> Agency_Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Module> DN_Module1 { get; set; }
        public virtual DN_Module DN_Module2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Role_ModuleActive> DN_Role_ModuleActive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_User_ModuleActive> DN_User_ModuleActive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Roles> DN_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Users> DN_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ST_Group> ST_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
