//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_News_Comment
    {
        public int ID { get; set; }
        public Nullable<int> NewsSSCID { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Message { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
        public Nullable<int> IsLevel { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<int> AgencyID { get; set; }
    
        public virtual DN_NewsSSC DN_NewsSSC { get; set; }
        public virtual DN_Users DN_Users { get; set; }
    }
}
