//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Promotion
    {
        public DN_Promotion()
        {
            this.Product_Promotion = new HashSet<Product_Promotion>();
            this.Promotion_Product = new HashSet<Promotion_Product>();
            this.Categories = new HashSet<Category>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> DateStart { get; set; }
        public Nullable<decimal> DateEnd { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsAll { get; set; }
        public Nullable<bool> IsEnd { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<bool> IsAgency { get; set; }
        public Nullable<System.Guid> UserCreate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> UserUpdate { get; set; }
        public Nullable<int> QuantityUse { get; set; }
        public Nullable<decimal> TotalOrder { get; set; }
        public Nullable<bool> IsOnly { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual DN_Users DN_Users { get; set; }
        public virtual DN_Users DN_Users1 { get; set; }
        public virtual ICollection<Product_Promotion> Product_Promotion { get; set; }
        public virtual ICollection<Promotion_Product> Promotion_Product { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
    }
}
