//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Packet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DN_Packet()
        {
            this.DN_Product_Packet = new HashSet<DN_Product_Packet>();
            this.DN_Bed_Desk = new HashSet<DN_Bed_Desk>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<bool> IsEarly { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> TimeEarly { get; set; }
        public Nullable<int> TimeWait { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Product_Packet> DN_Product_Packet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Bed_Desk> DN_Bed_Desk { get; set; }
    }
}
