//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Product_Packet
    {
        public int ID { get; set; }
        public int ProductId { get; set; }
        public int PacketID { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual DN_Packet DN_Packet { get; set; }
        public virtual Shop_Product Shop_Product { get; set; }
    }
}
