//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DN_Question()
        {
            this.DN_Results_Questions = new HashSet<DN_Results_Questions>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<bool> Sort { get; set; }
        public Nullable<bool> IsShow { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Results_Questions> DN_Results_Questions { get; set; }
    }
}
