//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_RequestWareSupplier
    {
        public int Id { get; set; }
        public System.Guid RequestWareId { get; set; }
        public int SupplierId { get; set; }
        public decimal Quantity { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual DN_RequestWare DN_RequestWare { get; set; }
        public virtual DN_Supplier DN_Supplier { get; set; }
        public virtual DN_Users DN_Users { get; set; }
    }
}
