//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Roles
    {
        public DN_Roles()
        {
            this.DN_Role_ModuleActive = new HashSet<DN_Role_ModuleActive>();
            this.DN_UsersInRoles = new HashSet<DN_UsersInRoles>();
            this.DN_Active = new HashSet<DN_Active>();
            this.DN_Calendar = new HashSet<DN_Calendar>();
            this.DN_Criteria = new HashSet<DN_Criteria>();
            this.DN_Module = new HashSet<DN_Module>();
        }
    
        public System.Guid RoleId { get; set; }
        public string RoleName { get; set; }
        public string LoweredRoleName { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public string Description { get; set; }
        public Nullable<int> LevelId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int ID { get; set; }
    
        public virtual DN_Agency DN_Agency { get; set; }
        public virtual DN_Level DN_Level { get; set; }
        public virtual ICollection<DN_Role_ModuleActive> DN_Role_ModuleActive { get; set; }
        public virtual ICollection<DN_UsersInRoles> DN_UsersInRoles { get; set; }
        public virtual ICollection<DN_Active> DN_Active { get; set; }
        public virtual ICollection<DN_Calendar> DN_Calendar { get; set; }
        public virtual ICollection<DN_Criteria> DN_Criteria { get; set; }
        public virtual ICollection<DN_Module> DN_Module { get; set; }
    }
}
