//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_RequestWare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DN_RequestWare()
        {
            this.Cate_Value = new HashSet<Cate_Value>();
            this.DN_RequestWareDetail = new HashSet<DN_RequestWareDetail>();
            this.DN_RequestWareSupplier = new HashSet<DN_RequestWareSupplier>();
            this.MapProduceRequestWares = new HashSet<MapProduceRequestWare>();
        }
    
        public System.Guid GID { get; set; }
        public Nullable<int> StorageProductID { get; set; }
        public Nullable<int> CateID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<decimal> Date { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> Today { get; set; }
        public Nullable<int> Hour { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<decimal> DateUpdate { get; set; }
        public Nullable<decimal> QuantityActive { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<int> MarketID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<decimal> DateEnd { get; set; }
        public Nullable<decimal> QuantityUsed { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> Sale { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cate_Value> Cate_Value { get; set; }
        public virtual Category Category { get; set; }
        public virtual DN_Agency DN_Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_RequestWareDetail> DN_RequestWareDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_RequestWareSupplier> DN_RequestWareSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MapProduceRequestWare> MapProduceRequestWares { get; set; }
        public virtual Market Market { get; set; }
        public virtual StorageWarehousing StorageWarehousing { get; set; }
    }
}
