//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_RequestWarehousing
    {
        public int ID { get; set; }
        public Nullable<int> StorageProductID { get; set; }
        public Nullable<int> CateValueID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<decimal> Date { get; set; }
        public Nullable<decimal> DateEnd { get; set; }
        public string BarCode { get; set; }
        public string Imei { get; set; }
    
        public virtual Cate_Value Cate_Value { get; set; }
        public virtual StorageWarehousing StorageWarehousing { get; set; }
    }
}
