//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DN_Room()
        {
            this.DN_Bed_Desk = new HashSet<DN_Bed_Desk>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> Row { get; set; }
        public Nullable<int> Column { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Bed_Desk> DN_Bed_Desk { get; set; }
        public virtual DN_Level DN_Level { get; set; }
    }
}
