//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Salary
    {
        public int ID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<int> CriteriaId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
    
        public virtual DN_Criteria DN_Criteria { get; set; }
        public virtual DN_Users DN_Users { get; set; }
    }
}
