//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Status
    {
        public DN_Status()
        {
            this.DN_Bed_Desk = new HashSet<DN_Bed_Desk>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public Nullable<int> AgencyID { get; set; }
    
        public virtual ICollection<DN_Bed_Desk> DN_Bed_Desk { get; set; }
    }
}
