//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DN_Schedule()
        {
            this.DN_EDIT_Schedule = new HashSet<DN_EDIT_Schedule>();
            this.DN_Time_Job = new HashSet<DN_Time_Job>();
            this.DN_Time_Job1 = new HashSet<DN_Time_Job>();
            this.DN_Weekly_Schedule = new HashSet<DN_Weekly_Schedule>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> HoursStart { get; set; }
        public Nullable<int> MinuteStart { get; set; }
        public Nullable<int> HoursEnd { get; set; }
        public Nullable<int> MinuteEnd { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Sort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_EDIT_Schedule> DN_EDIT_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Time_Job> DN_Time_Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Time_Job> DN_Time_Job1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Weekly_Schedule> DN_Weekly_Schedule { get; set; }
    }
}
