//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Supplie
    {
        public DN_Supplie()
        {
            this.Debts = new HashSet<Debt>();
            this.Order_Debt = new HashSet<Order_Debt>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string TaxCode { get; set; }
        public string NameCompaly { get; set; }
        public string AddressCompany { get; set; }
        public string Credits { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> DateCreate { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public string Note { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<bool> IsLook { get; set; }
        public Nullable<int> EnterpriseId { get; set; }
    
        public virtual ICollection<Debt> Debts { get; set; }
        public virtual ICollection<Order_Debt> Order_Debt { get; set; }
    }
}
