//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Setting
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string Description { get; set; }
        public Nullable<int> EnterpriseID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> AgencyID { get; set; }
    
        public virtual DN_Agency DN_Agency { get; set; }
        public virtual Position Position { get; set; }
        public virtual Type Type { get; set; }
    }
}
