//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DN_Supplier()
        {
            this.DN_RequestWareSupplier = new HashSet<DN_RequestWareSupplier>();
            this.DN_SupplierProduct = new HashSet<DN_SupplierProduct>();
            this.OrderCars = new HashSet<OrderCar>();
            this.SupplierAmountProducts = new HashSet<SupplierAmountProduct>();
            this.TotalProductToDays = new HashSet<TotalProductToDay>();
            this.Documents = new HashSet<Document>();
            this.Shop_Product_Comingsoon = new HashSet<Shop_Product_Comingsoon>();
            this.StorageProducts = new HashSet<StorageProduct>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string TaxCode { get; set; }
        public string NameCompaly { get; set; }
        public string AddressCompany { get; set; }
        public string Credits { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> DateCreate { get; set; }
        public Nullable<int> EnterpriseID { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public string Note { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<bool> IsLook { get; set; }
    
        public virtual DN_Agency DN_Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_RequestWareSupplier> DN_RequestWareSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_SupplierProduct> DN_SupplierProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCar> OrderCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierAmountProduct> SupplierAmountProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TotalProductToDay> TotalProductToDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_Product_Comingsoon> Shop_Product_Comingsoon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageProduct> StorageProducts { get; set; }
    }
}
