//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_TypeCriteria
    {
        public DN_TypeCriteria()
        {
            this.DN_Criteria = new HashSet<DN_Criteria>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> IsPercent { get; set; }
    
        public virtual ICollection<DN_Criteria> DN_Criteria { get; set; }
    }
}
