//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Time_Job
    {
        public int ID { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<decimal> DateEnd { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<int> ScheduleEndID { get; set; }
        public Nullable<int> MinutesLater { get; set; }
        public Nullable<int> MinutesEarly { get; set; }
    
        public virtual DN_Schedule DN_Schedule { get; set; }
        public virtual DN_Schedule DN_Schedule1 { get; set; }
        public virtual DN_Users DN_Users { get; set; }
    }
}
