//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Tree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DN_Tree()
        {
            this.DN_ContentVote = new HashSet<DN_ContentVote>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ListID { get; set; }
        public Nullable<int> UserInRoleID { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_ContentVote> DN_ContentVote { get; set; }
        public virtual DN_UsersInRoles DN_UsersInRoles { get; set; }
    }
}
