//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_UsersInRoles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DN_UsersInRoles()
        {
            this.DN_Tree = new HashSet<DN_Tree>();
        }
    
        public int ID { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid RoleId { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual DN_Department DN_Department { get; set; }
        public virtual DN_Roles DN_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Tree> DN_Tree { get; set; }
        public virtual DN_Users DN_Users { get; set; }
    }
}
