//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_User_ModuleActive
    {
        public int ID { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> ActiveId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Check { get; set; }
        public Nullable<int> AgencyId { get; set; }
    
        public virtual DN_Active DN_Active { get; set; }
        public virtual DN_Module DN_Module { get; set; }
        public virtual DN_Users DN_Users { get; set; }
    }
}
