//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_User_BedDesk
    {
        public int ID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<int> BedDeskID { get; set; }
        public Nullable<int> MWSID { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
        public Nullable<int> AgencyID { get; set; }
    
        public virtual DN_Bed_Desk DN_Bed_Desk { get; set; }
        public virtual DN_Users DN_Users { get; set; }
        public virtual DN_Weekly_Schedule DN_Weekly_Schedule { get; set; }
    }
}
