//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DN_Users()
        {
            this.Banners = new HashSet<Banner>();
            this.Banners1 = new HashSet<Banner>();
            this.CashAdvances = new HashSet<CashAdvance>();
            this.CashAdvances1 = new HashSet<CashAdvance>();
            this.CashAdvances2 = new HashSet<CashAdvance>();
            this.Category_Recipe = new HashSet<Category_Recipe>();
            this.Companies = new HashSet<Company>();
            this.Cost_Product_User = new HashSet<Cost_Product_User>();
            this.Debts = new HashSet<Debt>();
            this.DN_ContentVote = new HashSet<DN_ContentVote>();
            this.DN_Discount = new HashSet<DN_Discount>();
            this.DN_Discount1 = new HashSet<DN_Discount>();
            this.DN_EDIT_Schedule = new HashSet<DN_EDIT_Schedule>();
            this.DN_EDIT_Schedule1 = new HashSet<DN_EDIT_Schedule>();
            this.DN_Export = new HashSet<DN_Export>();
            this.DN_Export1 = new HashSet<DN_Export>();
            this.DN_ExportProduct = new HashSet<DN_ExportProduct>();
            this.DN_ExportProduct1 = new HashSet<DN_ExportProduct>();
            this.DN_ImportProduct = new HashSet<DN_ImportProduct>();
            this.DN_ImportProduct1 = new HashSet<DN_ImportProduct>();
            this.DN_Login = new HashSet<DN_Login>();
            this.DN_Mail_SSC = new HashSet<DN_Mail_SSC>();
            this.DN_Mail_SSC1 = new HashSet<DN_Mail_SSC>();
            this.DN_News_Comment = new HashSet<DN_News_Comment>();
            this.DN_Promotion = new HashSet<DN_Promotion>();
            this.DN_Promotion1 = new HashSet<DN_Promotion>();
            this.DN_RequestWareSupplier = new HashSet<DN_RequestWareSupplier>();
            this.DN_Salary = new HashSet<DN_Salary>();
            this.DN_Sale = new HashSet<DN_Sale>();
            this.DN_Sale1 = new HashSet<DN_Sale>();
            this.DN_Time_Job = new HashSet<DN_Time_Job>();
            this.DN_Total_SalaryMonth = new HashSet<DN_Total_SalaryMonth>();
            this.DN_User_BedDesk = new HashSet<DN_User_BedDesk>();
            this.DN_User_ModuleActive = new HashSet<DN_User_ModuleActive>();
            this.DN_UsersInRoles = new HashSet<DN_UsersInRoles>();
            this.OrderCars = new HashSet<OrderCar>();
            this.OrderCars1 = new HashSet<OrderCar>();
            this.Produces = new HashSet<Produce>();
            this.Produces1 = new HashSet<Produce>();
            this.ProduceCatogories = new HashSet<ProduceCatogory>();
            this.ProduceCatogories1 = new HashSet<ProduceCatogory>();
            this.ProduceProductPrepares = new HashSet<ProduceProductPrepare>();
            this.ProduceProductPrepares1 = new HashSet<ProduceProductPrepare>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PurchaseOrders1 = new HashSet<PurchaseOrder>();
            this.StorageWarehousingLogs = new HashSet<StorageWarehousingLog>();
            this.StorageWarehousingUsers = new HashSet<StorageWarehousingUser>();
            this.SupplierAmountProducts = new HashSet<SupplierAmountProduct>();
            this.Documents = new HashSet<Document>();
            this.Order_Debt = new HashSet<Order_Debt>();
            this.P_Workshop = new HashSet<P_Workshop>();
            this.PaymentVouchers = new HashSet<PaymentVoucher>();
            this.PaymentVouchers1 = new HashSet<PaymentVoucher>();
            this.ProductCode_CostUser = new HashSet<ProductCode_CostUser>();
            this.ProductDetail_Recipe = new HashSet<ProductDetail_Recipe>();
            this.ReceiptPayments = new HashSet<ReceiptPayment>();
            this.ReceiptPayments1 = new HashSet<ReceiptPayment>();
            this.ReceiptVouchers = new HashSet<ReceiptVoucher>();
            this.ReceiveHistories = new HashSet<ReceiveHistory>();
            this.Repays = new HashSet<Repay>();
            this.Repays1 = new HashSet<Repay>();
            this.Shop_ContactOrder = new HashSet<Shop_ContactOrder>();
            this.Shop_Orders = new HashSet<Shop_Orders>();
            this.Shop_Orders1 = new HashSet<Shop_Orders>();
            this.Shop_Orders2 = new HashSet<Shop_Orders>();
            this.Shop_Product_Detail = new HashSet<Shop_Product_Detail>();
            this.Storages = new HashSet<Storage>();
            this.StorageFreightWarehouses = new HashSet<StorageFreightWarehouse>();
            this.StorageFreightWarehouses1 = new HashSet<StorageFreightWarehouse>();
            this.StorageProducts = new HashSet<StorageProduct>();
            this.DN_GroupEmail = new HashSet<DN_GroupEmail>();
            this.DN_Calendar = new HashSet<DN_Calendar>();
            this.DN_Module = new HashSet<DN_Module>();
            this.DN_Criteria = new HashSet<DN_Criteria>();
        }
    
        public System.Guid UserId { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string UserName { get; set; }
        public string LoweredUserName { get; set; }
        public Nullable<decimal> BirthDay { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> IsAnonymous { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public Nullable<decimal> StartDate { get; set; }
        public Nullable<decimal> CreateDate { get; set; }
        public Nullable<int> FixedSalary { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> YearLevel { get; set; }
        public Nullable<int> StartLevel { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsOut { get; set; }
        public string CodeCheckIn { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<bool> IsAgency { get; set; }
        public Nullable<bool> IsService { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banner> Banners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banner> Banners1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashAdvance> CashAdvances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashAdvance> CashAdvances1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashAdvance> CashAdvances2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category_Recipe> Category_Recipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cost_Product_User> Cost_Product_User { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Debt> Debts { get; set; }
        public virtual DN_Agency DN_Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_ContentVote> DN_ContentVote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Discount> DN_Discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Discount> DN_Discount1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_EDIT_Schedule> DN_EDIT_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_EDIT_Schedule> DN_EDIT_Schedule1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Export> DN_Export { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Export> DN_Export1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_ExportProduct> DN_ExportProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_ExportProduct> DN_ExportProduct1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_ImportProduct> DN_ImportProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_ImportProduct> DN_ImportProduct1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Login> DN_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Mail_SSC> DN_Mail_SSC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Mail_SSC> DN_Mail_SSC1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_News_Comment> DN_News_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Promotion> DN_Promotion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Promotion> DN_Promotion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_RequestWareSupplier> DN_RequestWareSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Salary> DN_Salary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Sale> DN_Sale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Sale> DN_Sale1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Time_Job> DN_Time_Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Total_SalaryMonth> DN_Total_SalaryMonth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_User_BedDesk> DN_User_BedDesk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_User_ModuleActive> DN_User_ModuleActive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_UsersInRoles> DN_UsersInRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCar> OrderCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCar> OrderCars1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produce> Produces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produce> Produces1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProduceCatogory> ProduceCatogories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProduceCatogory> ProduceCatogories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProduceProductPrepare> ProduceProductPrepares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProduceProductPrepare> ProduceProductPrepares1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageWarehousingLog> StorageWarehousingLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageWarehousingUser> StorageWarehousingUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierAmountProduct> SupplierAmountProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Debt> Order_Debt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_Workshop> P_Workshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentVoucher> PaymentVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentVoucher> PaymentVouchers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCode_CostUser> ProductCode_CostUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetail_Recipe> ProductDetail_Recipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptPayment> ReceiptPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptPayment> ReceiptPayments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptVoucher> ReceiptVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiveHistory> ReceiveHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repay> Repays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repay> Repays1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_ContactOrder> Shop_ContactOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_Orders> Shop_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_Orders> Shop_Orders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_Orders> Shop_Orders2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_Product_Detail> Shop_Product_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage> Storages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageFreightWarehouse> StorageFreightWarehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageFreightWarehouse> StorageFreightWarehouses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageProduct> StorageProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_GroupEmail> DN_GroupEmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Calendar> DN_Calendar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Module> DN_Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Criteria> DN_Criteria { get; set; }
    }
}
