//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_Weekly_Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DN_Weekly_Schedule()
        {
            this.DN_Calendar_Weekly_Schedule = new HashSet<DN_Calendar_Weekly_Schedule>();
            this.DN_User_BedDesk = new HashSet<DN_User_BedDesk>();
        }
    
        public int ID { get; set; }
        public Nullable<int> WeeklyID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_Calendar_Weekly_Schedule> DN_Calendar_Weekly_Schedule { get; set; }
        public virtual DN_Schedule DN_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_User_BedDesk> DN_User_BedDesk { get; set; }
        public virtual DN_Weekly DN_Weekly { get; set; }
    }
}
