//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.DocumentFiles = new HashSet<DocumentFile>();
            this.Wallet_Agency = new HashSet<Wallet_Agency>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string NoiBanHanh { get; set; }
        public string NguoiKy { get; set; }
        public string Description { get; set; }
        public Nullable<int> DrawerID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<decimal> DateApproval { get; set; }
        public Nullable<decimal> CreatedDate { get; set; }
        public Nullable<System.Guid> UserCreate { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> DateStart { get; set; }
        public Nullable<decimal> DateEnd { get; set; }
        public string Code { get; set; }
        public string NameB { get; set; }
        public string Address { get; set; }
        public string MST { get; set; }
        public string STK { get; set; }
        public string BankName { get; set; }
        public string Department { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string NameCompany { get; set; }
        public Nullable<bool> IsBill { get; set; }
        public string NumberBill { get; set; }
        public string MobieB { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public Nullable<decimal> DateCancel { get; set; }
        public string UserCancel { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> SupId { get; set; }
    
        public virtual DN_Agency DN_Agency { get; set; }
        public virtual DN_Drawer DN_Drawer { get; set; }
        public virtual DN_Supplier DN_Supplier { get; set; }
        public virtual DN_Users DN_Users { get; set; }
        public virtual ICollection<DocumentFile> DocumentFiles { get; set; }
        public virtual ICollection<Wallet_Agency> Wallet_Agency { get; set; }
    }
}
