//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentFile
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public string Folder { get; set; }
        public string FileUrl { get; set; }
        public Nullable<double> FileSize { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
