//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> FileID { get; set; }
        public Nullable<int> FEventID { get; set; }
    
        public virtual FDI_Event FDI_Event { get; set; }
        public virtual FDI_File FDI_File { get; set; }
    }
}
