//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export_Product_Value
    {
        public int ID { get; set; }
        public Nullable<int> ExportID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceExport { get; set; }
        public Nullable<int> ImportID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<decimal> Date { get; set; }
    
        public virtual DN_Export DN_Export { get; set; }
        public virtual DN_Import DN_Import { get; set; }
    }
}
