//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export_Product_Detail
    {
        public int ID { get; set; }
        public Nullable<int> StorageProductId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ValueId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Date { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Shop_Product Shop_Product { get; set; }
        public virtual Shop_Product_Value Shop_Product_Value { get; set; }
        public virtual StorageProduct StorageProduct { get; set; }
    }
}
