//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export_Product
    {
        public int ID { get; set; }
        public Nullable<int> ExportID { get; set; }
        public Nullable<int> InportProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Date { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual DN_ExportProduct DN_ExportProduct { get; set; }
    }
}
