//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAQ_Category()
        {
            this.FAQ_Category1 = new HashSet<FAQ_Category>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameAscii { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Description { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsShow { get; set; }
        public bool IsShowInTab { get; set; }
        public string LanguageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAQ_Category> FAQ_Category1 { get; set; }
        public virtual FAQ_Category FAQ_Category2 { get; set; }
    }
}
