//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ_Answer
    {
        public FAQ_Answer()
        {
            this.System_File = new HashSet<System_File>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string TitleAscii { get; set; }
        public int QuestionID { get; set; }
        public string Content { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsShow { get; set; }
    
        public virtual FAQ_Question FAQ_Question { get; set; }
        public virtual ICollection<System_File> System_File { get; set; }
    }
}
