//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HtmlMap
    {
        public int ID { get; set; }
        public Nullable<int> IdHtml { get; set; }
        public Nullable<int> IdModule { get; set; }
        public string LanguageId { get; set; }
        public Nullable<int> IdCopy { get; set; }
    
        public virtual HtmlContent HtmlContent { get; set; }
        public virtual ModuleControl ModuleControl { get; set; }
    }
}
