//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HtmlContent
    {
        public HtmlContent()
        {
            this.HtmlMaps = new HashSet<HtmlMap>();
        }
    
        public int ID { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<HtmlMap> HtmlMaps { get; set; }
    }
}
