//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string FallbackCulture { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Icon { get; set; }
        public Nullable<bool> IsShow { get; set; }
    
        public virtual Gallery_Picture Gallery_Picture { get; set; }
    }
}
