//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelVote
    {
        public LevelVote()
        {
            this.DN_ContentVote = new HashSet<DN_ContentVote>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<int> Soft { get; set; }
        public Nullable<int> AgencyID { get; set; }
    
        public virtual ICollection<DN_ContentVote> DN_ContentVote { get; set; }
    }
}
