//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuGroup
    {
        public MenuGroup()
        {
            this.Menus = new HashSet<Menu>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Des { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UserCreate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UserUpdate { get; set; }
        public Nullable<int> PortalId { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<int> AgencyID { get; set; }
    
        public virtual ICollection<Menu> Menus { get; set; }
    }
}
