//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Menus1 = new HashSet<Menu>();
        }
    
        public int Id { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public Nullable<int> PageId { get; set; }
        public Nullable<int> CateId { get; set; }
        public Nullable<int> Type { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
        public Nullable<int> IsLevel { get; set; }
        public Nullable<bool> IsNewTab { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LanguageId { get; set; }
        public Nullable<int> PortalId { get; set; }
        public string Icolor { get; set; }
        public Nullable<int> AgencyID { get; set; }
    
        public virtual MenuGroup MenuGroup { get; set; }
        public virtual ICollection<Menu> Menus1 { get; set; }
        public virtual Menu Menu1 { get; set; }
    }
}
