//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_Comment
    {
        public News_Comment()
        {
            this.Comment_Like = new HashSet<Comment_Like>();
            this.News_Comment1 = new HashSet<News_Comment>();
            this.News_CommentReport = new HashSet<News_CommentReport>();
        }
    
        public int ID { get; set; }
        public Nullable<int> NewsID { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> NewsCommentID { get; set; }
        public Nullable<bool> DatKPI { get; set; }
        public string LanguageId { get; set; }
    
        public virtual ICollection<Comment_Like> Comment_Like { get; set; }
        public virtual ICollection<News_Comment> News_Comment1 { get; set; }
        public virtual News_Comment News_Comment2 { get; set; }
        public virtual News_News News_News { get; set; }
        public virtual ICollection<News_CommentReport> News_CommentReport { get; set; }
    }
}
