//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News_News()
        {
            this.News_Comment = new HashSet<News_Comment>();
            this.News_News_Product = new HashSet<News_News_Product>();
            this.TM_News_Comment = new HashSet<TM_News_Comment>();
            this.Categories = new HashSet<Category>();
            this.System_File = new HashSet<System_File>();
            this.System_Tag = new HashSet<System_Tag>();
            this.Steps = new HashSet<Step>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string TitleAscii { get; set; }
        public Nullable<int> PictureID { get; set; }
        public string Description { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string LinkTinTuc { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> clicked { get; set; }
        public string link { get; set; }
        public string SEOTitle { get; set; }
        public string SEODescription { get; set; }
        public string SEOKeyword { get; set; }
        public string IP { get; set; }
        public Nullable<bool> NoIndex { get; set; }
        public Nullable<System.DateTime> StartDateDisplay { get; set; }
        public Nullable<bool> IsAppendID { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public Nullable<bool> IsSlide { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public Nullable<bool> IsAllowComment { get; set; }
        public Nullable<bool> IsFast { get; set; }
        public string LanguageId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sort { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserActive { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public string Author { get; set; }
        public Nullable<int> StepID { get; set; }
        public Nullable<int> catid { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.Guid> Modifier { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Gallery_Picture Gallery_Picture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News_Comment> News_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News_News_Product> News_News_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TM_News_Comment> TM_News_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_File> System_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Tag> System_Tag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Step> Steps { get; set; }
    }
}
