//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Package
    {
        public int ID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> Datecreate { get; set; }
        public Nullable<decimal> DateStart { get; set; }
        public Nullable<decimal> DateEnd { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer_Type Customer_Type { get; set; }
    }
}
