//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string NoOrder { get; set; }
        public Nullable<int> ContactOrderID { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        public Nullable<bool> IsTime { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public string Note { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string CustomerName { get; set; }
        public Nullable<byte> StatusPayment { get; set; }
        public string District { get; set; }
        public string Wards { get; set; }
        public decimal FeeShip { get; set; }
        public Nullable<int> CityID { get; set; }
        public string vpc_TransactionNo { get; set; }
        public Nullable<decimal> ShipViettelPost { get; set; }
        public Nullable<decimal> Total { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string Coupon { get; set; }
        public decimal CouponPrice { get; set; }
        public Nullable<int> CustomerAddressID { get; set; }
        public decimal Discount { get; set; }
        public Nullable<decimal> DateUpdateStatus { get; set; }
        public Nullable<byte> Check { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<int> ShopID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DN_Agency DN_Agency { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
