//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Debt
    {
        public int ID { get; set; }
        public Nullable<decimal> Pricetotal { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> Datecreate { get; set; }
        public Nullable<int> SupplieId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
    
        public virtual DN_Users DN_Users { get; set; }
    }
}
