//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Workshop
    {
        public P_Workshop()
        {
            this.OrderCars = new HashSet<OrderCar>();
            this.Category_Recipe = new HashSet<Category_Recipe>();
            this.ProductDetail_Recipe = new HashSet<ProductDetail_Recipe>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> DateActive { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
        public string Latitute { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual DN_Users DN_Users { get; set; }
        public virtual ICollection<OrderCar> OrderCars { get; set; }
        public virtual ICollection<Category_Recipe> Category_Recipe { get; set; }
        public virtual ICollection<ProductDetail_Recipe> ProductDetail_Recipe { get; set; }
    }
}
