//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Page()
        {
            this.Widgets = new HashSet<Widget>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string UrlFile { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
        public string Value { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> FlieID { get; set; }
    
        public virtual FDI_File FDI_File { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Widget> Widgets { get; set; }
    }
}
