//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments_Order
    {
        public int ID { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> MethodId { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> DateCreate { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Payment_Method Payment_Method { get; set; }
        public virtual Shop_Orders Shop_Orders { get; set; }
    }
}
