//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Reading
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> Page { get; set; }
        public Nullable<bool> IsTime { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
