//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail_Recipe
    {
        public ProductDetail_Recipe()
        {
            this.Mapping_ProductDetail_Recipe = new HashSet<Mapping_ProductDetail_Recipe>();
            this.ProductValue_Recipe = new HashSet<ProductValue_Recipe>();
            this.P_Workshop = new HashSet<P_Workshop>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProductDetailId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<decimal> DateCreate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> ValuePrice { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<decimal> DateUpdate { get; set; }
        public Nullable<int> TimeM { get; set; }
        public Nullable<decimal> Incurred { get; set; }
        public string Code { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsUse { get; set; }
    
        public virtual DN_Users DN_Users { get; set; }
        public virtual ICollection<Mapping_ProductDetail_Recipe> Mapping_ProductDetail_Recipe { get; set; }
        public virtual Shop_Product_Detail Shop_Product_Detail { get; set; }
        public virtual ICollection<ProductValue_Recipe> ProductValue_Recipe { get; set; }
        public virtual ICollection<P_Workshop> P_Workshop { get; set; }
    }
}
