//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduceProductDetail
    {
        public int ID { get; set; }
        public int ProduceId { get; set; }
        public int ProductId { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<int> SizeId { get; set; }
        public decimal Weight { get; set; }
        public Nullable<int> ProductParentId { get; set; }
    
        public virtual Produce Produce { get; set; }
        public virtual Shop_Product_Detail Shop_Product_Detail { get; set; }
        public virtual Product_Size Product_Size { get; set; }
    }
}
