//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Promotion
    {
        public int ID { get; set; }
        public Nullable<int> PromotionID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual DN_Promotion DN_Promotion { get; set; }
        public virtual Shop_Product_Detail Shop_Product_Detail { get; set; }
    }
}
