//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Size
    {
        public Product_Size()
        {
            this.ProduceProductDetails = new HashSet<ProduceProductDetail>();
            this.Shop_Product = new HashSet<Shop_Product>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<int> UnitID { get; set; }
    
        public virtual ICollection<ProduceProductDetail> ProduceProductDetails { get; set; }
        public virtual ICollection<Shop_Product> Shop_Product { get; set; }
    }
}
