//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCode_CostUser
    {
        public int ID { get; set; }
        public Nullable<int> ProductCodeID { get; set; }
        public Nullable<int> CostUserID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> UserCreated { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
        public string Note { get; set; }
    
        public virtual Cost_Product_User Cost_Product_User { get; set; }
        public virtual DN_Users DN_Users { get; set; }
        public virtual ProductCode ProductCode { get; set; }
    }
}
