//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductValue_Recipe
    {
        public int ID { get; set; }
        public Nullable<int> ProductValueId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> DateCreate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> RecipeID { get; set; }
    
        public virtual ProductDetail_Recipe ProductDetail_Recipe { get; set; }
        public virtual Shop_Product_Value Shop_Product_Value { get; set; }
    }
}
