//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produce
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produce()
        {
            this.MapProduceRequestWares = new HashSet<MapProduceRequestWare>();
            this.ProduceCatogories = new HashSet<ProduceCatogory>();
            this.ProduceProductDetails = new HashSet<ProduceProductDetail>();
            this.ProduceProductPrepares = new HashSet<ProduceProductPrepare>();
            this.Product_Value = new HashSet<Product_Value>();
        }
    
        public int ID { get; set; }
        public int ProductId { get; set; }
        public decimal Quantity { get; set; }
        public System.Guid UserId { get; set; }
        public decimal DateCreate { get; set; }
        public Nullable<System.Guid> UserUpdate { get; set; }
        public Nullable<decimal> DateUpdate { get; set; }
        public bool Isdelete { get; set; }
        public decimal ToDayCode { get; set; }
        public int Status { get; set; }
        public decimal DateProduce { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual DN_Users DN_Users { get; set; }
        public virtual DN_Users DN_Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MapProduceRequestWare> MapProduceRequestWares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProduceCatogory> ProduceCatogories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProduceProductDetail> ProduceProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProduceProductPrepare> ProduceProductPrepares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Value> Product_Value { get; set; }
    }
}
