//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRating
    {
        public ProductRating()
        {
            this.Gallery_Picture = new HashSet<Gallery_Picture>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int TypeRating { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Shop_Product Shop_Product { get; set; }
        public virtual ICollection<Gallery_Picture> Gallery_Picture { get; set; }
    }
}
