//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion_Procuct
    {
        public int ID { get; set; }
        public Nullable<int> PromotionId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<decimal> Sale { get; set; }
        public string mode { get; set; }
    
        public virtual Promotion Promotion { get; set; }
    }
}
