//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            this.Cate_Value = new HashSet<Cate_Value>();
        }
    
        public int ID { get; set; }
        public Nullable<int> OrderCarId { get; set; }
        public int Quantity { get; set; }
        public decimal Weight { get; set; }
        public int Status { get; set; }
        public Nullable<System.Guid> UserCreated { get; set; }
        public Nullable<System.Guid> UserUpdate { get; set; }
        public decimal CreateDate { get; set; }
        public Nullable<decimal> UpdateDate { get; set; }
        public bool IsDelete { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Cate_Value> Cate_Value { get; set; }
        public virtual DN_Users DN_Users { get; set; }
        public virtual DN_Users DN_Users1 { get; set; }
        public virtual OrderCar OrderCar { get; set; }
    }
}
