//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiveHistory
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<decimal> Date { get; set; }
        public Nullable<decimal> DateCreate { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<int> BonusTypeId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> IdUser { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> DateActive { get; set; }
        public Nullable<int> CustomerIDR { get; set; }
        public string Query { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DN_Users DN_Users { get; set; }
        public virtual Shop_Orders Shop_Orders { get; set; }
    }
}
