//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleCode
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsUse { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<decimal> DateUse { get; set; }
    
        public virtual DN_Sale DN_Sale { get; set; }
    }
}
