//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Send_Card
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> DateCreate { get; set; }
        public Nullable<int> CardID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DN_Card DN_Card { get; set; }
    }
}
