//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_ContactOrder
    {
        public Shop_ContactOrder()
        {
            this.Shop_ContactOrder_Details = new HashSet<Shop_ContactOrder_Details>();
            this.Shop_Orders = new HashSet<Shop_Orders>();
            this.DN_Bed_Desk1 = new HashSet<DN_Bed_Desk>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<int> BedDeskID { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
        public Nullable<decimal> StartDate { get; set; }
        public Nullable<decimal> EndDate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> TotalMinute { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> Status { get; set; }
        public string AddressCompany { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string Company { get; set; }
        public string CodeCompany { get; set; }
        public string Mobile { get; set; }
        public string Content { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsEarly { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Payments { get; set; }
        public string Longitude { get; set; }
        public string Latitute { get; set; }
        public decimal ReceiveDate { get; set; }
        public int ReceiveHour { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DN_Agency DN_Agency { get; set; }
        public virtual DN_Bed_Desk DN_Bed_Desk { get; set; }
        public virtual DN_Users DN_Users { get; set; }
        public virtual ICollection<Shop_ContactOrder_Details> Shop_ContactOrder_Details { get; set; }
        public virtual ICollection<Shop_Orders> Shop_Orders { get; set; }
        public virtual ICollection<DN_Bed_Desk> DN_Bed_Desk1 { get; set; }
    }
}
