//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Order_Details
    {
        public long ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ComboID { get; set; }
        public Nullable<int> QuantityOld { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string ContentPromotion { get; set; }
        public Nullable<bool> IsPromotion { get; set; }
        public Nullable<int> PromotionProductID { get; set; }
        public Nullable<decimal> PriceSale { get; set; }
        public Nullable<decimal> Percent { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Barcode { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> ProductValueID { get; set; }
        public Nullable<int> CateValueID { get; set; }
        public Nullable<System.Guid> ImportProductGID { get; set; }
        public Nullable<int> StatusPayment { get; set; }
        public Nullable<bool> IsPrestige { get; set; }
        public Nullable<int> Check { get; set; }
        public Nullable<decimal> DateUpdateStatus { get; set; }
    
        public virtual Cate_Value Cate_Value { get; set; }
        public virtual DN_Combo DN_Combo { get; set; }
        public virtual DN_ImportProduct DN_ImportProduct { get; set; }
        public virtual Product_Value Product_Value { get; set; }
        public virtual Promotion_Product Promotion_Product { get; set; }
        public virtual Shop_Orders Shop_Orders { get; set; }
        public virtual Shop_Product Shop_Product { get; set; }
    }
}
