//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int ID { get; set; }
        public string MaCuaHang { get; set; }
        public string TenCuaHang { get; set; }
        public string NguoiDaiDien { get; set; }
        public string DienThoai { get; set; }
        public string Website { get; set; }
        public string DiaChi { get; set; }
        public string LinhVucKinhDoanh { get; set; }
        public string masothue { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
