//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Product_Value
    {
        public Shop_Product_Value()
        {
            this.DN_Import = new HashSet<DN_Import>();
            this.Export_Product_Detail = new HashSet<Export_Product_Detail>();
            this.ProductValue_Recipe = new HashSet<ProductValue_Recipe>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameAscii { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QuantityOut { get; set; }
        public Nullable<int> QuantityDay { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ICollection<DN_Import> DN_Import { get; set; }
        public virtual DN_Unit DN_Unit { get; set; }
        public virtual ICollection<Export_Product_Detail> Export_Product_Detail { get; set; }
        public virtual ICollection<ProductValue_Recipe> ProductValue_Recipe { get; set; }
    }
}
