//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Brands
    {
        public Shop_Brands()
        {
            this.Category_ShopBrand = new HashSet<Category_ShopBrand>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameAscii { get; set; }
        public string Link { get; set; }
        public string Description { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<int> PictureID { get; set; }
        public Nullable<int> LogoPictureID { get; set; }
        public string LanguageId { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Code { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string TaxCode { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Category_ShopBrand> Category_ShopBrand { get; set; }
        public virtual Gallery_Picture Gallery_Picture { get; set; }
    }
}
