//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Orders
    {
        public Shop_Orders()
        {
            this.Customer_Review = new HashSet<Customer_Review>();
            this.Payments_Order = new HashSet<Payments_Order>();
            this.ReceiveHistories = new HashSet<ReceiveHistory>();
            this.RewardAgencyHistories = new HashSet<RewardAgencyHistory>();
            this.RewardHistories = new HashSet<RewardHistory>();
            this.Shop_Order_Details = new HashSet<Shop_Order_Details>();
            this.WalletOrder_History = new HashSet<WalletOrder_History>();
            this.DN_Bed_Desk1 = new HashSet<DN_Bed_Desk>();
        }
    
        public int ID { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> UserCreate { get; set; }
        public Nullable<System.Guid> UserIdBedDeskID { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<int> BedDeskID { get; set; }
        public Nullable<int> ContactOrderID { get; set; }
        public Nullable<int> TotalMinute { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
        public Nullable<decimal> StartDate { get; set; }
        public Nullable<decimal> EndDate { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> Payments { get; set; }
        public decimal Discount { get; set; }
        public Nullable<decimal> PrizeMoney { get; set; }
        public Nullable<decimal> Deposits { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> PriceReceipt { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string Company { get; set; }
        public string CodeCompany { get; set; }
        public string Mobile { get; set; }
        public string AddressCompany { get; set; }
        public Nullable<bool> IsEarly { get; set; }
        public Nullable<int> AddMinuteID { get; set; }
        public string Billnumber { get; set; }
        public string TaxCode { get; set; }
        public string CompanyName { get; set; }
        public Nullable<decimal> SalePercent { get; set; }
        public string SaleCode { get; set; }
        public Nullable<bool> Isinvoice { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> TotalSaleSP { get; set; }
        public string OrderCode { get; set; }
        public Nullable<decimal> TotalPriceTranfer { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> ReceiveDate { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string Code { get; set; }
        public decimal FeeShip { get; set; }
        public Nullable<int> StatusPayment { get; set; }
        public string Coupon { get; set; }
        public Nullable<int> ShopID { get; set; }
        public decimal CouponPrice { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<int> CustomerAddressID { get; set; }
        public Nullable<int> Check { get; set; }
        public Nullable<decimal> DateUpdateStatus { get; set; }
    
        public virtual AddMinute AddMinute { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Customer_Review> Customer_Review { get; set; }
        public virtual CustomerAddress CustomerAddress { get; set; }
        public virtual DN_Agency DN_Agency { get; set; }
        public virtual DN_Bed_Desk DN_Bed_Desk { get; set; }
        public virtual DN_Users DN_Users { get; set; }
        public virtual DN_Users DN_Users1 { get; set; }
        public virtual DN_Users DN_Users2 { get; set; }
        public virtual ICollection<Payments_Order> Payments_Order { get; set; }
        public virtual ICollection<ReceiveHistory> ReceiveHistories { get; set; }
        public virtual ICollection<RewardAgencyHistory> RewardAgencyHistories { get; set; }
        public virtual ICollection<RewardHistory> RewardHistories { get; set; }
        public virtual Shop_ContactOrder Shop_ContactOrder { get; set; }
        public virtual ICollection<Shop_Order_Details> Shop_Order_Details { get; set; }
        public virtual ICollection<WalletOrder_History> WalletOrder_History { get; set; }
        public virtual ICollection<DN_Bed_Desk> DN_Bed_Desk1 { get; set; }
    }
}
