//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source_Video
    {
        public int ID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> VideoID { get; set; }
        public Nullable<decimal> DateCreate { get; set; }
        public Nullable<int> Sort { get; set; }
    
        public virtual Gallery_Video Gallery_Video { get; set; }
        public virtual Source Source { get; set; }
    }
}
