//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageWarehousingUser
    {
        public int Id { get; set; }
        public Nullable<int> StorageWarehousingId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual DN_Users DN_Users { get; set; }
        public virtual StorageWarehousing StorageWarehousing { get; set; }
    }
}
