//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageWarehousingLog
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public int StorageWarehousingId { get; set; }
        public string ActionName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
    
        public virtual DN_Users DN_Users { get; set; }
        public virtual StorageWarehousing StorageWarehousing { get; set; }
    }
}
