//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_File
    {
        public System_File()
        {
            this.FAQ_Answer = new HashSet<FAQ_Answer>();
            this.News_Job = new HashSet<News_Job>();
            this.News_News = new HashSet<News_News>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public byte[] Data { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual System_FileType System_FileType { get; set; }
        public virtual ICollection<FAQ_Answer> FAQ_Answer { get; set; }
        public virtual ICollection<News_Job> News_Job { get; set; }
        public virtual ICollection<News_News> News_News { get; set; }
    }
}
