//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Config
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string PhoneMobile { get; set; }
        public string PhoneAdvice { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string BusinessLicence { get; set; }
        public string PhoneAdvice1 { get; set; }
        public string PhoneAdvice2 { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public string Website { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Email2 { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string EmailSend { get; set; }
        public string EmailSendPwd { get; set; }
        public string EmailReceive { get; set; }
        public string LanguageId { get; set; }
        public string SEOTitle { get; set; }
        public string SEODescription { get; set; }
        public string SEOKeyword { get; set; }
        public string Embedmaps { get; set; }
    }
}
