//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public System_City()
        {
            this.Areas = new HashSet<Area>();
            this.GoogleMaps = new HashSet<GoogleMap>();
            this.System_District = new HashSet<System_District>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool IsShow { get; set; }
        public string Description { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string GroupLocation { get; set; }
        public string CodeWerther { get; set; }
        public Nullable<bool> IsWerther { get; set; }
        public string LanguageID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Area> Areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoogleMap> GoogleMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_District> System_District { get; set; }
    }
}
