//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Tag
    {
        public System_Tag()
        {
            this.Category_Tags = new HashSet<Category_Tags>();
            this.News_Job = new HashSet<News_Job>();
            this.News_News = new HashSet<News_News>();
            this.Shop_Product_Detail = new HashSet<Shop_Product_Detail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public string NameAscii { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Link { get; set; }
        public string SEOTitle { get; set; }
        public string SEODescription { get; set; }
        public string SEOKeyword { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsReadMore { get; set; }
        public string LanguageId { get; set; }
        public string Url { get; set; }
    
        public virtual ICollection<Category_Tags> Category_Tags { get; set; }
        public virtual ICollection<News_Job> News_Job { get; set; }
        public virtual ICollection<News_News> News_News { get; set; }
        public virtual ICollection<Shop_Product_Detail> Shop_Product_Detail { get; set; }
    }
}
