//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Therapy_History
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> DateCreate { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Note { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> AgencyID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
