//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Module_Rating
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TM_Module_Rating()
        {
            this.TM_Rate_Comment = new HashSet<TM_Rate_Comment>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> TM_CustomerID { get; set; }
        public string Content { get; set; }
        public Nullable<double> RateAvg { get; set; }
        public Nullable<double> NumberRate { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
        public Nullable<decimal> DateActive { get; set; }
        public string UserActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsShow { get; set; }
    
        public virtual Shop_Product Shop_Product { get; set; }
        public virtual TM_Customer TM_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TM_Rate_Comment> TM_Rate_Comment { get; set; }
    }
}
