//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_News_Comment
    {
        public int ID { get; set; }
        public Nullable<int> NewID { get; set; }
        public Nullable<int> TM_CustomerID { get; set; }
        public string Message { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
        public Nullable<decimal> DateActive { get; set; }
        public Nullable<decimal> UserActive { get; set; }
        public Nullable<int> NumberLike { get; set; }
        public Nullable<int> NoLike { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual News_News News_News { get; set; }
        public virtual TM_Customer TM_Customer { get; set; }
    }
}
