//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenDevice
    {
        public int ID { get; set; }
        public string Token { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string UserId { get; set; }
        public string App { get; set; }
    }
}
