//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalProductToDay
    {
        public int ID { get; set; }
        public decimal ToDayCode { get; set; }
        public decimal Quantity { get; set; }
        public int SupplierId { get; set; }
        public int ProductId { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Note { get; set; }
        public int Status { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public decimal DateCreated { get; set; }
        public decimal Price { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual DN_Supplier DN_Supplier { get; set; }
    }
}
