//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public Type()
        {
            this.DN_Setting = new HashSet<DN_Setting>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Name { get; set; }
    
        public virtual ICollection<DN_Setting> DN_Setting { get; set; }
    }
}
