//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_Border
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public W_Border()
        {
            this.W_Decoration = new HashSet<W_Decoration>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<long> ColorID { get; set; }
        public string BorderStyle { get; set; }
    
        public virtual W_Base W_Base { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<W_Decoration> W_Decoration { get; set; }
    }
}
