//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public W_Category()
        {
            this.W_Base = new HashSet<W_Base>();
            this.W_Category1 = new HashSet<W_Category>();
            this.W_Effect = new HashSet<W_Effect>();
            this.W_Spacer = new HashSet<W_Spacer>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> Input { get; set; }
        public Nullable<int> Output { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<W_Base> W_Base { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<W_Category> W_Category1 { get; set; }
        public virtual W_Category W_Category2 { get; set; }
        public virtual W_RoleCate W_RoleCate { get; set; }
        public virtual W_Supplier W_Supplier { get; set; }
        public virtual W_Type W_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<W_Effect> W_Effect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<W_Spacer> W_Spacer { get; set; }
    }
}
