//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_Effect
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public W_Effect()
        {
            this.W_Decoration = new HashSet<W_Decoration>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Value { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> CateID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<double> BlurRadius { get; set; }
        public Nullable<double> OffsetX { get; set; }
        public Nullable<double> OffsetY { get; set; }
        public Nullable<double> SpreadRadius { get; set; }
        public Nullable<int> ColorR { get; set; }
        public Nullable<int> ColorG { get; set; }
        public Nullable<int> ColorB { get; set; }
        public Nullable<double> ColorA { get; set; }
    
        public virtual W_Category W_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<W_Decoration> W_Decoration { get; set; }
        public virtual W_Supplier W_Supplier { get; set; }
        public virtual W_Type W_Type { get; set; }
    }
}
