//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_Radius
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public W_Radius()
        {
            this.W_Decoration = new HashSet<W_Decoration>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> TopLeft { get; set; }
        public Nullable<double> TopRight { get; set; }
        public Nullable<double> BottomLeft { get; set; }
        public Nullable<double> BottomRight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<W_Decoration> W_Decoration { get; set; }
    }
}
