//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_RoleCate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public W_RoleCate()
        {
            this.W_Category = new HashSet<W_Category>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsFrame { get; set; }
        public Nullable<bool> IsOpacity { get; set; }
        public Nullable<bool> IsPosition { get; set; }
        public Nullable<bool> IsMargin { get; set; }
        public Nullable<bool> IsDecoration { get; set; }
        public Nullable<bool> IsTextStyle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<W_Category> W_Category { get; set; }
    }
}
