//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_Spacer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> CateID { get; set; }
        public Nullable<int> TypeID { get; set; }
    
        public virtual W_Category W_Category { get; set; }
        public virtual W_Supplier W_Supplier { get; set; }
        public virtual W_Type W_Type { get; set; }
    }
}
