//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_TextStyle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public W_TextStyle()
        {
            this.W_Style = new HashSet<W_Style>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> FontSize { get; set; }
        public Nullable<double> Height { get; set; }
        public string FontWeight { get; set; }
        public Nullable<long> ColorSkinID { get; set; }
        public Nullable<int> MaxLines { get; set; }
        public string TextAlign { get; set; }
        public Nullable<long> TypoSkinID { get; set; }
        public string TextOverflow { get; set; }
        public Nullable<bool> SoftWrap { get; set; }
        public Nullable<double> TextScaleFactor { get; set; }
        public string TextWidthBasis { get; set; }
        public string TextDecoration { get; set; }
    
        public virtual W_Base W_Base { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<W_Style> W_Style { get; set; }
    }
}
