//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletCustomer
    {
        public WalletCustomer()
        {
            this.RewardHistories = new HashSet<RewardHistory>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> DateCreate { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Type { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> UserActive { get; set; }
        public Nullable<decimal> DateActive { get; set; }
        public string Code { get; set; }
        public Nullable<int> CustomerIDR { get; set; }
        public string Transaction_no { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<RewardHistory> RewardHistories { get; set; }
    }
}
