//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Widget()
        {
            this.APIs = new HashSet<API>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public Nullable<int> PagetID { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string UrlFile { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<decimal> DateCreated { get; set; }
        public string Value { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> FileID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<API> APIs { get; set; }
        public virtual FDI_File FDI_File { get; set; }
        public virtual Page Page { get; set; }
    }
}
